# Database Configuration
spring.application.name=gardenguardian
spring.datasource.url=jdbc:postgresql://localhost:5432/garden_calculator
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.agritech.gardenplanner=DEBUG
logging.level.web=DEBUG

# Application Configuration
#app.name=Garden Planner
app.version=1.0.0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=agritech.innovators20@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true